### ISSUE TITLE
Possible memory leak problem?

### ISSUE THREAD

**Issue by acepor** [TeamHG-Memex/sklearn-crfsuite#18]
Hi @kmike 

My colleagues used a Java version of CRFSuite, and found a memory leak problem in it. Therefore, we checked the original CRFsuite site, and found there are a number of issues related to this problem:
[Results in chokkan/crfsuite](https://github.com/chokkan/crfsuite/search?q=memory+leak&type=Issues&utf8=%E2%9C%93). The latest fix accepted by the author is in 2016, and there are some more recent commits by other contributors. 

When we read the doc of Python-CRFsuite, the latest fix of this issue is back to 2015. Can you tell us if the latest Python-CRFSuite or sklearn-CRFSuite fixed those problems? Many thanks!

**Comment by kmike** [comment]
Hi @acepor,

python-crfsuite currently uses this CRFSuite commit: https://github.com/chokkan/crfsuite/commits/387ca696e698d2d2865337acb1ee52a46b086749. It includes all merged memory-related fixes. We're not using latest python-crfsuite because it breaks compatibility with older Visual Studios, and this breaks python-crfsuite on Windows with Python < 3.4 (including 2.x).

But there are unmerged memory-related fixes, and the commit we're using is not compatible with more recent VS versions. It seems to move forward we need to create crfsuite fork, merge all good pull requests (there is a few of them, they are hangng for a long time), and use this fork instead - it looks like CRFSuite author is busy these days and doesn't have enough time to update the library.

**Comment by acepor** [comment]
Thanks a lot for the explanation!

**Comment by kmike** [comment]
Update: the issue was fixed in python-crfsuite; CRFSuite C++ library finally got updated. The fix will be available in python-crfsuite 0.9.3 release.
