### ISSUE TITLE
TypeError: 'numpy.int64' object is not iterable

### ISSUE THREAD

**Issue by tastyminerals** [TeamHG-Memex/sklearn-crfsuite#19]
I am playing with a script that runs the same dataset on 7 sklearn classifiers. Just bumped into sklearn-crfsuite and decided to include it into the train-test loop. However, I am getting numpy type error on the following line:

```
self.classifier.fit(feats_train, feats_train)
```
where `self.classifier` is sklearn classifier instance, ` CRF(algorithm='lbfgs', c1=0.1, c2=0.1,
                           max_iterations=100, all_possible_transitions=True)` 
`feats_train` -- pandas Dataframe 
`targets_train` -- pandas Series

Concretely:

`feats_train`
```
      feat1  feat2    feat3  
0      -1       -1        7   
1      11       -1      702  
2      -1        5        1    
3       1       -1       74    
4      11        2       -1       
(...)
```
`feats_train`
```
        target
0       0
1       1
2       0
3       1
(...)
```

All sklearn classifiers trained and tested without errors on the same data while sklearn-crfsuite complains about the input having the same API. Is it a bug or should I modify my input somehow?

**Comment by kmike** [comment]
sklearn-crfsuite works with a very different input type than built-in sklearn classifiers; it takes a list of sequences of feature dicts. First, it does sequence prediction problem, so it accepts a list of sequences of varying length, not just a list/matrix of instances. Second, it doesn its own feature vectorization, so it doesn't take matrices as an input. 

You can't use it instead of e.g. sklearn.svm.SVC (and vice versa), as they're solving different tasks. Check the tutorial - https://sklearn-crfsuite.readthedocs.io/en/latest/tutorial.html.
