### ISSUE TITLE
How to create features with  duplicate keys ?

### ISSUE THREAD

**Issue by TechBK** [TeamHG-Memex/sklearn-crfsuite#23]
I see in (crfsuite document)[http://www.chokkan.org/software/crfsuite/manual.html] that key of feature can be duplicate:
```text
B-NP    w[1..4]=a:2 w[1..4]=man w[1..4]=eats
B-NP    w[1..4]=a w[1..4]=a w[1..4]=man w[1..4]=eats
B-NP    w[1..4]=a:2.0 w[1..4]=man:1.0 w[1..4]=eats:1.0
```
How to create features with  duplicate keys if i using sklearn-crfsuite ?

**Comment by kmike** [comment]
There are no duplicate features here: for example, in a first row `w[1..4]=a` and `w[1..4]=man` are feature names; `w[1..4]=a` has a value = 2 (`:2`), and `w[1..4]=man` has a default value = 1. `=` sign is just a convention to build readable feature names.

**Comment by TechBK** [comment]
In [crfsuite document](http://www.chokkan.org/software/crfsuite/manual.html):
-> This is the BNF notation representing the data format.
```
<line>           ::= <item> | <eos>
<item>           ::= <label> ('\t' <attribute>)+ <br>
<eos>            ::= <br>
<label>          ::= <string>
<attribute>      ::= <name> | <name> ':' <scaling>
<name>           ::= (<letter> | "\:" | "\\")+
<scaling>        ::= <numeric>
<br>             ::= '\n'
```

It mean `2` is `scaling` or `weight`.

A sample data for CRFsuite:
![A sample data for CRFsuite](http://www.chokkan.org/software/crfsuite/data_sample.png)

**Comment by kmike** [comment]
Yes, 2 is weight, this is what I've written as well.. Could you please provide an example of a duplicate key? It seems I don't understand your question.

**Comment by kmike** [comment]
See data format examples at http://python-crfsuite.readthedocs.io/en/latest/pycrfsuite.html#pycrfsuite.ItemSequence - the format you're using is just a shortcut:

> {“string_key”: “string_value”, ...} dict; that’s the same as {“string_key=string_value”: 1.0, ...}

All features have float values, both in crfsuite and python-crfsuite; `{"w[-1]": "a"}` is just a shortcut for `{"w[-1]=a": 1.0}`, and in crfsuite example `=` is just a convention. 1.0 is an assumed value; in crfsuite you override it by putting after `:`, in python-crfsuite you can override it by using another feature format (`{"string_key": float_value}`). 

So if you want such disjunctive features, pass `{"w[1...3]=eats": 1.0}` instead of `{"w[1...3]": "eats"}`. If you don't need weights, you can also use a list feature format.

**Comment by TechBK** [comment]
Ok. I think that if i pass `{"w[1...3]=eats": 1.0}`, it be like i pass `w[1...3]=eats=1.0:1.0`.

>  If you don't need weights, you can also use a list feature format.

-> How i use a list feature format with `sklearn-crfsuite` ?

**Comment by kmike** [comment]
`{"w[1...3]=eats": 1.0}` is exactly the same as `{"w[1...3]": "eats"}`. 

If all of your features have value 1.0, and you build feature names manually, you can pass a list: `["w[1...3]=eats", "w[1...3]=some", ...]` instead of a dict `{"w[1...3]": "eats", "w[1...3]": "some", ...}`, they are exactly the same. 

Please check data formats here: http://python-crfsuite.readthedocs.io/en/latest/pycrfsuite.html#pycrfsuite.ItemSequence

**Comment by TechBK** [comment]
Understood. Thank you.
